module.exports = {
  Admin: require('./admin.model'),
  AdminNotification: require('./admin-notification.model'),
  ConsentEvent: require('./consent-event.model'),
  ConversationBackup: require('./conversation-backup.model'),
  Conversation: require('./conversation.model'),
  ConversationMessage: require('./conversation-message.model'),
  ContactGroup: require('./contact-group.model'),
  Contact: require('./contact.model'),
  InviteClick: require('./invite-click.model'),
  Invite: require('./invite.model'),
  Log: require('./log.model'),
  Notification: require('./notification.model'),
  ProviderReceipt: require('./provider-receipt.model'),
  ProfileAuthChallenge: require('./profile-auth-challenge.model'),
  RefreshToken: require('./refresh-token.model'),
  Setting: require('./setting.model'),
  Template: require('./template.model'),
  TemplateSet: require('./template-set.model'),
  Term: require('./term.model'),
  WhatsappCloudWebhookEvent: require('./whatsapp-cloud-webhook-event.model')
};
